export const LOAD_ALL_CATEGORIES = 'LOAD_ALL_CATEGORIES';
export const LOAD_MY_CATEGORIES = 'LOAD_MY_CATEGORIES';

export const MY_BASIC_INFO = 'MY_BASIC_INFO';

export const SESSION_EXPIRED = 'SESSION_EXPIRED';