export const LOAD_ALL_CATEGORIES = 'LOAD_ALL_CATEGORIES';
export const LOAD_MY_CATEGORIES = 'LOAD_MY_CATEGORIES';

export const CURRENT_USER_ID = 'CURRENT_USER_ID';

export const SESSION_EXPIRED = 'SESSION_EXPIRED';