export const LOAD_ALL_CATEGORIES = 'LOAD_ALL_CATEGORIES';
export const LOAD_MY_CATEGORIES = 'LOAD_MY_CATEGORIES';
export const DELETE_CATEGORY = 'DELETE_CATEGORY';

export const MY_BASIC_INFO = 'MY_BASIC_INFO';

export const SET_CURRENT_CATEGORY = 'SET_CURRENT_CATEGORY';
export const SET_CURRENT_SEARCH = 'SET_CURRENT_SEARCH';
export const SET_CURRENT_VIEW = 'SET_CURRENT_VIEW';
export const SET_CURRENT_FEED_URL = 'SET_CURRENT_FEED_URL';

export const SET_GENERAL_ERROR = 'SET_GENERAL_ERROR';

export const SESSION_EXPIRED = 'SESSION_EXPIRED';